ztjhz/BetterChatGPT

- src/components/ApiMenu/ApiMenu.tsx
The issue with the code lies in the handleSave function of the ApiMenu component, specifically in the if (apiFree === true) condition. When apiFree is true, the handleSave function closes the modal, regardless of whether the user selected "Use your own API key" or "Use free API provided by Ayaka" before clicking the "Cancel" button. This means that the configuration is not being reverted back to "Free" even though the user canceled the selection of their own API key.
To fix the bug, we will need to update the handleSave function to properly handle the "Cancel" button. One approach is to introduce a new state variable called selectedApiFree that tracks the user's selected API option. We can set it to the initial value of apiFree, and update it whenever the user toggles the radio buttons. …
> Bug Fix #21

- package.json
- src/store/store.ts
- yarn.lock
This pull request updates the application to fix the following deprecation warnings:
- 'GetState' is deprecated. You might be looking for StateCreator, if not then use StoreApi<T>['getState'] instead of GetState<T>.
- 'SetState' is deprecated. You might be looking for StateCreator, if not then use StoreApi<T>['setState'] instead of SetState<T>.
- 'create' is deprecated. Use import { create } from 'zustand' instead.
The changes include updating the imports and types in store.ts and modifying the parameters of the store slice functions to use StoreApi instead of GetState and SetState.
I have tested the changes locally to make sure that they do not introduce any regressions.
> Add fixes for deprecation warnings

- src/components/ApiMenu/ApiMenu.tsx
- src/store/auth-slice.ts
I am currently transitioning from Cloudflare to Google Cloud Run, and the process of updating the domain name DNS records will take some time. During this period, the domain name for the API must be changed to the default domain name provided by Google Cloud Run. Once the DNS records have been updated, the domain name can be changed back to its original setting. See https://github.com/ayaka14732/ChatGPTAPIFree/pull/13.
> Temporarily change the free API endpoint URL

- src/components/ApiMenu/ApiMenu.tsx
- src/store/auth-slice.ts
The migration process for issue #55 has now been completed. The free API URL can now be changed back to its original setting.
> Restore original free API URL

- src/i18n.ts
Thank you for this project, it has solved the frustration of frequently losing connection when using the official https://chat.openai.com.
When I forked and deployed this project in GitHub Page myself, I found that **it loaded the i18n files from the root path**, e.g., `https://username.github.io/locales/zh-CN/main.json`. However, my GitHub Page URL is `https://username.github.io/FreeChatGPT`.
It loads i18n files starting from the base url, e.g., `https://username.github.io/FreeChatGPT/locales/zh-CN/main.json`.
It loads i18n files starting from the root path, e.g., `https://username.github.io/locales/zh-CN/main.json`.
1. Opens `F12 Developer Tools`.
2. Enters the website https://lujunbofan2019.github.io/FreeChatGPT/
3. Watchs the requests in `Developer Tools`.
1. Opens `F12 Developer …
> fix: locating i18n files error

- .github/workflows/deploy.yml
- README-zh_CN.md
- README.md
Pros:
* It saves a step for users who want to deploy their own [FreeChatGPT](https://github.com/ztjhz/FreeChatGPT).
* It provides additional security for the repository since the GitHub Page workflow requires write access, but not all workflows do.
> ci: enable write permission in workflow

- public/locales/fr/main.json
Better use "Soumettre" instead of "Envoyer" to translate "Submit". "Envoyer" is more contextually translation for the word "Send"
> little fix a french translation contextual word

- src/components/Menu/ChatFolder.tsx
- src/components/Menu/NewChat.tsx
- tailwind.config.cjs
* Display it at the top instead at the end. This because chats are ordered by recently created.
UX issue when clicking to the button at the end,
and have to scroll at the top to see and edit newly created chat.
* Display the button when hovering the folder, not just the group of chats in the folder.
This make the button to display when hover the folder, even if there is not yet chats list in the folder.
> adjust new chat button display in chat folder

- src/components/Chat/ChatContent/Message/CommandPrompt/CommandPrompt.tsx
- src/components/Menu/ChatFolder.tsx
Added an event listener to hide dropdown, 
when anything other than the dropdown is clicked, 
implemented via a click event.
> Refact: hide dropdown prompt & palette when clicked outside 

- package.json
The mac version's icon was left as Electron's initial icon, so I fixed it so that it shows the same icon as the other versions.
- befor
- after
> Fixed icons for mac version

- src/utils/date.ts
Improves the readability and efficiency of the getToday function by using template literals and the padStart method. By using template literals, the code is more concise and easier to read. The padStart method ensures that both the month and day have two digits, which simplifies the string construction process. This change maintains the functionality of the original code while improving the overall quality and maintainability of the function.
> Refactor getToday function for improved readability and efficiency

- electron/index.cjs
- public/locales/en-US/main.json
- public/locales/en/main.json
- src/components/Chat/ChatContent/Message/CommandPrompt/CommandPrompt.tsx
- src/components/Menu/MenuOptions/ClearConversation.tsx
- src/components/Menu/MenuOptions/MenuOptions.tsx
- src/components/SettingsMenu/SettingsMenu.tsx
Making a PR to bring over some of the most non-controversial tweaks that I've made for my custom mirror.
- Hid the Electron Menu Bar (File, Edit, View, etc.)
- Automatically focusing the search bar when opening the Command Prompt Library search
- Moved Clear Conversation Button into settings to make it harder to accidentally press + take up less screen real-estate
I have quite a few other custom tweaks on my mirror, but I'm prioritizing personal preference and utility over aesthetics for much of it.
> gpt.koaladev.io cherrypicked tweaks

- electron/index.cjs
fixed crash on attempting to open new instance, required refactoring BrowserWindow to global:
`Uncaught Exception:
ReferenceError: win is not defined
at click (C:\Users\jacks\AppData\Local\Programs\better-chatgpt\resources\app.asar\electron\index.cjs:53:9)
at MenuItem.click (node:electron/js2c/browser_init:2:30166)
at a._executeCommand (node:electron/js2c/browser_init:2:35562)
`
fixed crash on attempting to open new instance, required refactoring BrowserWindow:
`Uncaught Exception:
ReferenceError: win is not defined
at click (C:\Users\jacks\AppData\Local\Programs\better-chatgpt\resources\app.asar\electron\index.cjs:53:9)
at MenuItem.click (node:electron/js2c/browser_init:2:30166)
at a._executeCommand (node:electron/js2c/browser_init:2:35562)`
> Fixed 2 Electron Crashes

- src/api/api.ts
This is a fix for the Azure OpenAI API requests mentioned here #296
> Azure OpenAI API Fix

- src/components/Menu/ChatHistory.tsx
Add a title attribue to the div showing the chat title.
This helps to quickly see the full title on hover
> Show title for when the title is too long

- src/api/api.ts
- src/hooks/useSubmit.ts
Description:
Issue: #401 
- Azure's GPT4 model response doesn't seem to contain the `delta` field in each `choice`, add null check to ignore the empty content
- Add Azure OpenAI GPT 4 models for building API endpoint
> Add support for Azure OpenAI GPT4

- electron/index.cjs
I enjoy using the electron app, however, I miss being able to spell correct words, open links in a new browser window, and most of the context menu items you would see in a browser window. Hence this PR adds punch of these
https://github.com/ztjhz/BetterChatGPT/assets/5157350/4428e617-d18e-487d-933e-0de0a848ea19
> Electron context menu and links

- src/constants/chat.ts
- src/types/chat.ts
I've taken the pricing from https://openai.com/pricing which is the same as the current gpt-4-1106-preview
> Added gpt-4-0125-preview as a model option

- src/constants/chat.ts
There is an important typo in the latest `gpt-4-0125-preview` context length. 
It should be 128k instead of 4k as in `gpt-4-1106-preview`.
https://github.com/ztjhz/BetterChatGPT/blob/ecad41fd729cb36968aa4866391692d02a51af89/src/constants/chat.ts#L50-L51
source: https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
closes https://github.com/ztjhz/BetterChatGPT/issues/533
cc: @ztjhz
> fix a typo in gpt-4-0125 context length

- README.md
Updating the readme to show the minimum version of node and npm required to run BetterGPT Locally.
> Adding Node/NPM version info to the readme

- README.md
- docker-compose.yml
Added docker compose instructions so people can run the app locally using Docker
> Added docker compose instructions
